/** `mindi init` — creates a .env configuration file. */

import fs from "node:fs";
import path from "node:path";
import { header, success, warn, info, error, colors } from "../format.js";

const ENV_TEMPLATE = `# MINDI Runtime configuration
# Generated by: mindi init

# Default primary model provider + model
MINDI_DEFAULT_PROVIDER=openai
MINDI_DEFAULT_MODEL=gpt-4o-mini

# OpenAI-compatible provider (supports OpenAI, OpenRouter, Groq, Together, etc.)
OPENAI_API_KEY=
OPENAI_BASE_URL=https://api.openai.com/v1
OPENAI_ORG_ID=

# Google Gemini provider
GEMINI_API_KEY=

# Runtime options
MINDI_LOG_LEVEL=info
MINDI_REQUEST_TIMEOUT_MS=120000
MINDI_TOOL_TIMEOUT_MS=30000
MINDI_MAX_HISTORY_MESSAGES=50
`;

export function initCommand(opts: { force?: boolean }): void {
  const envPath = path.join(process.cwd(), ".env");

  header("MINDI Runtime — Initialize");

  if (fs.existsSync(envPath) && !opts.force) {
    warn(".env file already exists. Use --force to overwrite.");
    return;
  }

  fs.writeFileSync(envPath, ENV_TEMPLATE, "utf8");
  success(`Created .env at ${envPath}`);

  info("Next steps:");
  process.stdout.write(`  ${colors.dim("1.")} Edit .env and add your API keys\n`);
  process.stdout.write(`  ${colors.dim("2.")} Run ${colors.cyan("mindi doctor")} to verify configuration\n`);
  process.stdout.write(`  ${colors.dim("3.")} Run ${colors.cyan("mindi run")} to execute a request\n\n`);

  if (!process.env.OPENAI_API_KEY && !process.env.GEMINI_API_KEY) {
    warn("No API keys detected. Add OPENAI_API_KEY or GEMINI_API_KEY to .env.");
    error("At least one provider must be configured to use the runtime.");
  }
}
